version: '3.4'
services:
  db:
    environment:
      - POSTGRES_USER=foreman
      - POSTGRES_PASSWORD=foreman
      - POSTGRES_DATABASE=foreman
      - PGDATA=/var/lib/postgresql/data/pgdata
#    hostname: db.example.com
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5432 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: ["postgres", "-c", "log_statement=all","-c","log_duration=on","-c","log_min_messages=INFO"]
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  app: &app_base
    #image: quay.io/foreman/foreman:develop
    image: janniswarnat/foreman:3.2-stable
    #command: bundle exec rdebug-ide --host 0.0.0.0 --port 1235 --dispatcher-port 26162 -- bin/rails server -b 0.0.0.0
    command: bundle exec bin/rails server -b 0.0.0.0
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://foreman:foreman@db/foreman?pool=5
      - RAILS_MAX_THREADS=5
      - RAILS_ENV=production
      - FOREMAN_FQDN=foreman.example.com
      - FOREMAN_DOMAIN=example.com
      - FOREMAN_RAILS_CACHE_STORE_TYPE=redis
      - FOREMAN_RAILS_CACHE_STORE_URLS=redis://redis:6379/0
      - DYNFLOW_REDIS_URL=redis://redis-tasks:6379/0
      - REDIS_PROVIDER=DYNFLOW_REDIS_URL
      - FOREMAN_LOGGING_LEVEL=debug
      - FOREMAN_LOGGING_PRODUCTION_TYPE=stdout
      - FOREMAN_LOGGING_PRODUCTION_LAYOUT=pattern #json
      # enables debugging from IDE and fixes performance issues
      - FOREMAN_PUMA_WORKERS=0
    hostname: foreman #.example.com
    links:
      - db
      - redis-cache
      - redis-tasks
    ports:
      - "3000:3000"
      - "5910-5930:5910-5930"
      - "1235:1235"
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

  orchestrator:
    <<: *app_base
    command: bundle exec sidekiq -r ./extras/dynflow-sidekiq.rb -c 1 -q dynflow_orchestrator
    #hostname: orchestrator.example.com
    ports: []

  worker:
    <<: *app_base
    command: bundle exec sidekiq -r ./extras/dynflow-sidekiq.rb -c 15 -q default,remote_execution
    ports: []

  redis-cache:
    image: redis
    ports:
      - "6379"
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  redis-tasks:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-persistent:/data
    ports:
      - "6379"
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  salt:
    image: "janniswarnat/salt:latest"
    build: ./build_master
    ports:
      - "4505-4506:4505-4506"
      - "8000:8000"
      - "9000:9000"
      - "1234:1234"
    entrypoint: ["/bin/sh", "-c" , "mkdir -p /srv/salt && tar -xzvf /tmp/salt-files.tar.gz -C /srv/salt && mkdir -p /etc/salt/pki/master/minions && cp /tmp/docker-salt-minion /etc/salt/pki/master/minions && cp /tmp/raspberrypi /etc/salt/pki/master/minions && cp /tmp/linksmart-black.iot /etc/salt/pki/master/minions && /usr/bin/supervisord"]
    configs:
      - source: master-pem
        target: "/etc/salt/pki/master/master.pem"
      - source: master-pub
        target: "/etc/salt/pki/master/master.pub"
      - source: minion-pub
        target: "/tmp/docker-salt-minion"
      - source: raspberrypi-pub
        target: "/tmp/raspberrypi"
      - source: linksmart-black-iot-pub
        target: "/tmp/linksmart-black.iot"
      - source: settings-yml
        target: "/github.com/smart-proxy/config/settings.yml"
      - source: salt-yml
        target: "/github.com/smart-proxy/config/settings.d/salt.yml"
      - source: dynflow-yml
        target: "/github.com/smart-proxy/config/settings.d/dynflow.yml"
      - source: foreman-conf
        target: "/etc/salt/master.d/foreman.conf"
      - source: foreman-yaml
        target: "/etc/salt/foreman.yaml"
      - source: supervisor-conf
        target: "/etc/supervisor/supervisord.conf"
      - source: salt-files
        target: "/tmp/salt-files.tar.gz"
      - source: pillar-top
        target: "/srv/pillar/top.sls"
      - source: pillar-default
        target: "/srv/pillar/default.sls"
      - source: pillar-raspberrypi
        target: "/srv/pillar/raspberrypi.sls"
      - source: pillar-linksmart
        target: "/srv/pillar/linksmart.sls"
    environment:
      - SALT_SHARED_SECRET=GCUrcjS8J5wrcdtbWpjV
      - 'SALT_MASTER_CONFIG={
                              "log_level": "info",
                              "file_roots": {
                                "base": [
                                  "/srv/salt/"
                                ]
                              },
                              "pillar_roots": {
                                "base": [
                                  "/srv/pillar/"
                                ]
                              }
                            }
                            '
      - 'SALT_API_CONFIG={
                            "rest_cherrypy":{
                               "port":8000,
                               "disable_ssl":true
                            },
                            "external_auth":{
                               "sharedsecret":{
                                  "salt":[
                                     ".*",
                                     "@wheel",
                                     "@jobs",
                                     "@runner"
                                  ]
                               }
                            },
                            "sharedsecret":"GCUrcjS8J5wrcdtbWpjV"
                         }
                         '
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
    labels:
      kompose.service.type: loadbalancer
      kompose.service.expose: "true"

  salt-minion:
    image: "janniswarnat/salt-minion:latest"
    build: ./build_minion
    entrypoint: ["salt-minion", "--log-level", "info"]
    configs:
      - source: minion-pem
        target: "/etc/salt/pki/minion/minion.pem"
      - source: minion-pub
        target: "/etc/salt/pki/minion/minion.pub"
      - source: minion
        target: /etc/salt/minion

volumes:
  db:
  redis-persistent:

configs:
  minion-pem:
    file: "./etc_minion/salt/pki/minion/minion.pem"
  minion-pub:
    file: "./etc_minion/salt/pki/minion/minion.pub"
  master-pem:
    file: "./etc_master/salt/pki/master/master.pem"
  master-pub:
    file: "./etc_master/salt/pki/master/master.pub"
  raspberrypi-pub:
    file: "./etc_master/salt/pki/master/minions/raspberrypi"
  linksmart-black-iot-pub:
    file: "./etc_master/salt/pki/master/minions/linksmart-black.iot"
  minion:
    file: "./etc_minion/salt/minion"
  settings-yml:
    file: "./etc_master/foreman-proxy/settings.yml"
  salt-yml:
    file: "./etc_master/foreman-proxy/settings.d/salt.yml"
  dynflow-yml:
    file: "./etc_master/foreman-proxy/settings.d/dynflow.yml"
  foreman-conf:
    file: "./etc_master/salt/master.d/foreman.conf"
  foreman-yaml:
    file: "./etc_master/salt/foreman.yaml"
  supervisor-conf:
    file: "./etc_master/supervisor/supervisord.conf"
  salt-files:
    file: "./srv/salt/salt-files.tar.gz"
  pillar-top:
    file: "./srv/pillar/top.sls"
  pillar-default:
    file: "./srv/pillar/default.sls"
  pillar-raspberrypi:
    file: "./srv/pillar/raspberrypi.sls"
  pillar-linksmart:
    file: "./srv/pillar/linksmart.sls"