apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.expose: "true"
    kompose.service.type: loadbalancer
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.expose: "true"
        kompose.service.type: loadbalancer
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - bundle
            - exec
            - sidekiq
            - -r
            - ./extras/dynflow-sidekiq.rb
            - -c
            - "15"
            - -q
            - default,remote_execution
          env:
            - name: DATABASE_URL
              value: postgres://foreman:foreman@db/foreman?pool=5
            - name: DYNFLOW_REDIS_URL
              value: redis://redis-tasks:6379/0
            - name: FOREMAN_DOMAIN
              value: example.com
            - name: FOREMAN_FQDN
              value: foreman.example.com
            - name: FOREMAN_LOGGING_LEVEL
              value: debug
            - name: FOREMAN_LOGGING_PRODUCTION_LAYOUT
              value: pattern
            - name: FOREMAN_LOGGING_PRODUCTION_TYPE
              value: stdout
            - name: FOREMAN_PUMA_WORKERS
              value: "0"
            - name: FOREMAN_RAILS_CACHE_STORE_TYPE
              value: redis
            - name: FOREMAN_RAILS_CACHE_STORE_URLS
              value: redis://redis:6379/0
            - name: RAILS_ENV
              value: production
            - name: RAILS_MAX_THREADS
              value: "5"
            - name: REDIS_PROVIDER
              value: DYNFLOW_REDIS_URL
          image: janniswarnat/foreman:3.2-stable
          livenessProbe:
            exec:
              command:
                - nc -z 127.0.0.1 3000 || exit 1
            initialDelaySeconds: 60
            periodSeconds: 300
          name: worker
          resources: {}
      hostname: foreman
      restartPolicy: Always
status: {}
